language: java
dist: trusty
install: skip

jobs:
  include:

    - stage: build
      jdk: openjdk8
      env: CONTRACT_TESTING_PACT__CONSUMER_ONE
      script:
        - cd contract-testing-pact/consumer-one
        - ./gradlew build
    - stage: build
      jdk: openjdk8
      env: CONTRACT_TESTING_PACT__CONSUMER_TWO
      script:
        - cd contract-testing-pact/consumer-two
        - ./gradlew build
    - stage: build
      jdk: openjdk8
      env: CONTRACT_TESTING_PACT__CONSUMER_PROVIDER
      script:
        - cd contract-testing-pact/provider
        - ./gradlew build

    - stage: build
      jdk: openjdk8
      env: SPRING_BOOT_AMQP
      services: docker
      sudo: required
      script:
        - cd spring-boot-amqp
        - ./gradlew build

    - stage: build
      jdk: openjdk8
      env: SPRING_BOOT_CACHE
      script:
        - cd spring-boot-cache
        - ./gradlew build

    - stage: build
      jdk: openjdk8
      env: SPRING_BOOT_FEIGN
      script:
        - cd spring-boot-feign
        - ./gradlew build

    - stage: build
      jdk: openjdk8
      env: SPRING_BOOT_JDBC
      script:
        - cd spring-boot-jdbc
        - ./gradlew build

    - stage: build
      jdk: openjdk8
      env: SPRING_BOOT_JPA
      script:
        - cd spring-boot-jpa
        - ./gradlew build

    - stage: build
      jdk: openjdk8
      env: SPRING_BOOT_MONGODB
      script:
        - cd spring-boot-mongodb
        - ./gradlew build

    - stage: build
      jdk: openjdk8
      env: SPRING_BOOT_WEB
      script:
        - cd spring-boot-web
        - ./gradlew build

    - stage: build
      jdk: openjdk8
      env: SPRING_CLOUD_FEIGN__EUREKA_SERVER
      script:
        - cd spring-cloud-feign/eureka-server
        - ./gradlew build
    - stage: build
      jdk: openjdk8
      env: SPRING_CLOUD_FEIGN__SERVICE_BAR
      script:
        - cd spring-cloud-feign/service-bar
        - ./gradlew build
    - stage: build
      jdk: openjdk8
      env: SPRING_CLOUD_FEIGN__SERVICE_FOO
      script:
        - cd spring-cloud-feign/service-foo
        - ./gradlew build
