mysql:
  image: mysql:5.7
  ports:
    - "3306:3306"
  restart: always
  environment:
    MYSQL_ROOT_PASSWORD: rootPassword
    MYSQL_DATABASE: database
    MYSQL_USER: user
    MYSQL_PASSWORD: password