name: Angular CI-Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

concurrency:
  group: ci_angular_${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci-angular:
    runs-on: ubuntu-latest
    needs:
      - angular
    steps:
      - run: echo "Angular CI-Build completed!"

  angular:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v2
        with:
          main-branch-name: 'master'
      - run: npm ci
        working-directory: ./angular
      - run: npx nx workspace-lint
        working-directory: ./angular
      - run: npx nx format:check --base=origin/master
        working-directory: ./angular
      - run: npx nx affected --target=lint --base=origin/master
        working-directory: ./angular
      - run: npx nx affected --target=test --base=origin/master --ci --code-coverage
        working-directory: ./angular
      - run: npx nx affected --target=e2e --base=origin/master
        working-directory: ./angular
      - run: npx nx affected --target=build --base=origin/master
        working-directory: ./angular
